from importlib import import_module

from src.market_radar.models import (
    CorrelationGroup,
    DataQuality,
    EtfDefinition,
    EtfComponentScores,
    EtfObservation,
    EtfSelection,
    EtfSelectionStatus,
    FactorBreakdown,
    MarketRegime,
    MarketRegimeAssessment,
    PositionPlan,
    PositionSuggestion,
    RadarRunSnapshot,
    RegimeComponents,
    SectorDefinition,
    SectorObservation,
    SectorScore,
    SectorState,
)

_LAZY_IMPORTS = {
    "CandidateSelector": "src.market_radar.candidates",
    "EnrichmentCandidate": "src.market_radar.candidates",
    "MarketRadarEnrichmentConfig": "src.market_radar.capabilities",
    "ProviderCapabilityAdapter": "src.market_radar.capability_provider",
    "EnrichmentBatch": "src.market_radar.enrichment",
    "MarketRadarEnricher": "src.market_radar.enrichment",
    "EtfCollectionBatch": "src.market_radar.etf_collection",
    "EtfCollectionConfig": "src.market_radar.etf_collection",
    "MarketRadarEtfCollector": "src.market_radar.etf_collection",
    "select_etfs": "src.market_radar.etf_selection",
    "LegacyRankingProvider": "src.market_radar.providers",
    "MarketRadarProvider": "src.market_radar.providers",
    "ProviderBatch": "src.market_radar.providers",
    "RankingConfig": "src.market_radar.ranking",
    "score_sectors": "src.market_radar.ranking",
    "MarketRadarReplayEngine": "src.market_radar.replay",
    "ReplayFrame": "src.market_radar.replay",
    "MarketRadarRepository": "src.market_radar.repository",
    "MarketRadarService": "src.market_radar.service",
    "EtfPolicyConfig": "src.market_radar.policy_config",
    "PositionPolicyConfig": "src.market_radar.policy_config",
    "RegimeConfig": "src.market_radar.policy_config",
    "build_position_plan": "src.market_radar.position_policy",
    "assess_market_regime": "src.market_radar.regime",
    "UniverseLoader": "src.market_radar.universe",
}


def __getattr__(name: str):
    module_name = _LAZY_IMPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value

__all__ = [
    "CandidateSelector",
    "CorrelationGroup",
    "DataQuality",
    "EnrichmentBatch",
    "EnrichmentCandidate",
    "EtfDefinition",
    "EtfComponentScores",
    "EtfCollectionBatch",
    "EtfCollectionConfig",
    "EtfObservation",
    "EtfPolicyConfig",
    "EtfSelection",
    "EtfSelectionStatus",
    "FactorBreakdown",
    "LegacyRankingProvider",
    "MarketRadarProvider",
    "MarketRadarEnricher",
    "MarketRadarEnrichmentConfig",
    "MarketRadarEtfCollector",
    "MarketRadarReplayEngine",
    "MarketRadarRepository",
    "MarketRadarService",
    "MarketRegime",
    "MarketRegimeAssessment",
    "PositionPlan",
    "PositionPolicyConfig",
    "PositionSuggestion",
    "ProviderBatch",
    "ProviderCapabilityAdapter",
    "RadarRunSnapshot",
    "RankingConfig",
    "ReplayFrame",
    "RegimeComponents",
    "RegimeConfig",
    "SectorDefinition",
    "SectorObservation",
    "SectorScore",
    "SectorState",
    "UniverseLoader",
    "assess_market_regime",
    "build_position_plan",
    "score_sectors",
    "select_etfs",
]
